site_name: Sasto Tickets B2C Documentation
# site_url: https://mydomain.org/mysite
theme:
  features:
    # - navigation.expand
    - navigation.sections
    - navigation.footer
    - content.tabs.link
  font:
    text: Inter   
  name: material
  palette:
    primary: red
copyright: Copyright &copy; 2024 Sasto Tickets Pvt. Ltd.
extra:
  generator: false
  meta:
    robots: "noindex, nofollow"
nav:
- Introduction : index.md
- Authorization : authorization.md
- Integration with Apps : getting-started.md
- Payment : payment.md
- Ticketing : ticketing.md
- Download eTicket : download.md
- Ticket Details : details.md
- Postman : postman.md
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true